/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Product,
  Uuid
} from '.././schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Retrieves a list of all registered products
 * @summary Get all products
 */
export const getApiV1Products = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Product[]>> => {
    
    
    return axios.get(
      `/api/v1/products`,options
    );
  }




export const getGetApiV1ProductsQueryKey = () => {
    return [
    `/api/v1/products`
    ] as const;
    }

    
export const getGetApiV1ProductsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Products>>, TError = AxiosError<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1Products>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ProductsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Products>>> = ({ signal }) => getApiV1Products({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Products>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1ProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Products>>>
export type GetApiV1ProductsQueryError = AxiosError<void>


/**
 * @summary Get all products
 */

export function useGetApiV1Products<TData = Awaited<ReturnType<typeof getApiV1Products>>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1Products>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1ProductsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Updates product details. Restricted to admin role.
 * @summary Update an existing product
 */
export const putApiV1Products = (
    product: Product, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Product>> => {
    
    
    return axios.put(
      `/api/v1/products`,
      product,options
    );
  }



export const getPutApiV1ProductsMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1Products>>, TError,{data: Product}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1Products>>, TError,{data: Product}, TContext> => {

const mutationKey = ['putApiV1Products'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1Products>>, {data: Product}> = (props) => {
          const {data} = props ?? {};

          return  putApiV1Products(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1ProductsMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1Products>>>
    export type PutApiV1ProductsMutationBody = Product
    export type PutApiV1ProductsMutationError = AxiosError<void>

    /**
 * @summary Update an existing product
 */
export const usePutApiV1Products = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1Products>>, TError,{data: Product}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1Products>>,
        TError,
        {data: Product},
        TContext
      > => {

      const mutationOptions = getPutApiV1ProductsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Registers a new product with its GTIN. Restricted to admin role.
 * @summary Create a new product
 */
export const postApiV1Products = (
    product: Product, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Product>> => {
    
    
    return axios.post(
      `/api/v1/products`,
      product,options
    );
  }



export const getPostApiV1ProductsMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Products>>, TError,{data: Product}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Products>>, TError,{data: Product}, TContext> => {

const mutationKey = ['postApiV1Products'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Products>>, {data: Product}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Products(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ProductsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Products>>>
    export type PostApiV1ProductsMutationBody = Product
    export type PostApiV1ProductsMutationError = AxiosError<void>

    /**
 * @summary Create a new product
 */
export const usePostApiV1Products = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Products>>, TError,{data: Product}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Products>>,
        TError,
        {data: Product},
        TContext
      > => {

      const mutationOptions = getPostApiV1ProductsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Retrieves a specific product by its UUID
 * @summary Get product by ID
 */
export const getApiV1ProductsId = (
    id: Uuid, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Product>> => {
    
    
    return axios.get(
      `/api/v1/products/${id}`,options
    );
  }




export const getGetApiV1ProductsIdQueryKey = (id?: Uuid,) => {
    return [
    `/api/v1/products/${id}`
    ] as const;
    }

    
export const getGetApiV1ProductsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ProductsId>>, TError = AxiosError<void>>(id: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductsId>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ProductsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ProductsId>>> = ({ signal }) => getApiV1ProductsId(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductsId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1ProductsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ProductsId>>>
export type GetApiV1ProductsIdQueryError = AxiosError<void>


/**
 * @summary Get product by ID
 */

export function useGetApiV1ProductsId<TData = Awaited<ReturnType<typeof getApiV1ProductsId>>, TError = AxiosError<void>>(
 id: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1ProductsId>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1ProductsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




