/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  PatchApiV1TasksIdStatusParams,
  Task,
  Uuid
} from '.././schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Assigns a new task to a worker within a specific farm
 * @summary Create a new task
 */
export const postApiV1Tasks = (
    task: Task, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/api/v1/tasks`,
      task,options
    );
  }



export const getPostApiV1TasksMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Tasks>>, TError,{data: Task}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Tasks>>, TError,{data: Task}, TContext> => {

const mutationKey = ['postApiV1Tasks'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Tasks>>, {data: Task}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Tasks(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TasksMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Tasks>>>
    export type PostApiV1TasksMutationBody = Task
    export type PostApiV1TasksMutationError = AxiosError<void>

    /**
 * @summary Create a new task
 */
export const usePostApiV1Tasks = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Tasks>>, TError,{data: Task}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Tasks>>,
        TError,
        {data: Task},
        TContext
      > => {

      const mutationOptions = getPostApiV1TasksMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Retrieves all tasks assigned to a specific worker
 * @summary Get tasks assigned to a user
 */
export const getApiV1TasksAssignedUsername = (
    username: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Task[]>> => {
    
    
    return axios.get(
      `/api/v1/tasks/assigned/${username}`,options
    );
  }




export const getGetApiV1TasksAssignedUsernameQueryKey = (username?: string,) => {
    return [
    `/api/v1/tasks/assigned/${username}`
    ] as const;
    }

    
export const getGetApiV1TasksAssignedUsernameQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TasksAssignedUsername>>, TError = AxiosError<void>>(username: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1TasksAssignedUsername>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TasksAssignedUsernameQueryKey(username);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TasksAssignedUsername>>> = ({ signal }) => getApiV1TasksAssignedUsername(username, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(username), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TasksAssignedUsername>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1TasksAssignedUsernameQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TasksAssignedUsername>>>
export type GetApiV1TasksAssignedUsernameQueryError = AxiosError<void>


/**
 * @summary Get tasks assigned to a user
 */

export function useGetApiV1TasksAssignedUsername<TData = Awaited<ReturnType<typeof getApiV1TasksAssignedUsername>>, TError = AxiosError<void>>(
 username: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1TasksAssignedUsername>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1TasksAssignedUsernameQueryOptions(username,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retrieves all tasks for a specific farm
 * @summary Get tasks for a farm
 */
export const getApiV1TasksFarmFarmId = (
    farmId: Uuid, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Task[]>> => {
    
    
    return axios.get(
      `/api/v1/tasks/farm/${farmId}`,options
    );
  }




export const getGetApiV1TasksFarmFarmIdQueryKey = (farmId?: Uuid,) => {
    return [
    `/api/v1/tasks/farm/${farmId}`
    ] as const;
    }

    
export const getGetApiV1TasksFarmFarmIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TasksFarmFarmId>>, TError = AxiosError<void>>(farmId: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1TasksFarmFarmId>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TasksFarmFarmIdQueryKey(farmId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TasksFarmFarmId>>> = ({ signal }) => getApiV1TasksFarmFarmId(farmId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(farmId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TasksFarmFarmId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1TasksFarmFarmIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TasksFarmFarmId>>>
export type GetApiV1TasksFarmFarmIdQueryError = AxiosError<void>


/**
 * @summary Get tasks for a farm
 */

export function useGetApiV1TasksFarmFarmId<TData = Awaited<ReturnType<typeof getApiV1TasksFarmFarmId>>, TError = AxiosError<void>>(
 farmId: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1TasksFarmFarmId>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1TasksFarmFarmIdQueryOptions(farmId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retrieves all tasks assigned to the currently authenticated user
 * @summary Get my assigned tasks
 */
export const getApiV1TasksMyTasks = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Task[]>> => {
    
    
    return axios.get(
      `/api/v1/tasks/my-tasks`,options
    );
  }




export const getGetApiV1TasksMyTasksQueryKey = () => {
    return [
    `/api/v1/tasks/my-tasks`
    ] as const;
    }

    
export const getGetApiV1TasksMyTasksQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TasksMyTasks>>, TError = AxiosError<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1TasksMyTasks>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TasksMyTasksQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TasksMyTasks>>> = ({ signal }) => getApiV1TasksMyTasks({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TasksMyTasks>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1TasksMyTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TasksMyTasks>>>
export type GetApiV1TasksMyTasksQueryError = AxiosError<void>


/**
 * @summary Get my assigned tasks
 */

export function useGetApiV1TasksMyTasks<TData = Awaited<ReturnType<typeof getApiV1TasksMyTasks>>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1TasksMyTasks>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1TasksMyTasksQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Allows a worker to mark as COMPLETED or a manager to mark as REVIEWED
 * @summary Update task status
 */
export const patchApiV1TasksIdStatus = (
    id: Uuid,
    params?: PatchApiV1TasksIdStatusParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.patch(
      `/api/v1/tasks/${id}/status`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPatchApiV1TasksIdStatusMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TasksIdStatus>>, TError,{id: Uuid;params?: PatchApiV1TasksIdStatusParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TasksIdStatus>>, TError,{id: Uuid;params?: PatchApiV1TasksIdStatusParams}, TContext> => {

const mutationKey = ['patchApiV1TasksIdStatus'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1TasksIdStatus>>, {id: Uuid;params?: PatchApiV1TasksIdStatusParams}> = (props) => {
          const {id,params} = props ?? {};

          return  patchApiV1TasksIdStatus(id,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1TasksIdStatusMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1TasksIdStatus>>>
    
    export type PatchApiV1TasksIdStatusMutationError = AxiosError<void>

    /**
 * @summary Update task status
 */
export const usePatchApiV1TasksIdStatus = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TasksIdStatus>>, TError,{id: Uuid;params?: PatchApiV1TasksIdStatusParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1TasksIdStatus>>,
        TError,
        {id: Uuid;params?: PatchApiV1TasksIdStatusParams},
        TContext
      > => {

      const mutationOptions = getPatchApiV1TasksIdStatusMutationOptions(options);

      return useMutation(mutationOptions);
    }
    