/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetApiV1InputBatchesLookupParams,
  InputBatch
} from '.././schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Retrieves all registered chemical and fertilizer lots
 * @summary List all inventory batches
 */
export const getApiV1InputBatches = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InputBatch[]>> => {
    
    
    return axios.get(
      `/api/v1/input-batches`,options
    );
  }




export const getGetApiV1InputBatchesQueryKey = () => {
    return [
    `/api/v1/input-batches`
    ] as const;
    }

    
export const getGetApiV1InputBatchesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1InputBatches>>, TError = AxiosError<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1InputBatches>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1InputBatchesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1InputBatches>>> = ({ signal }) => getApiV1InputBatches({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1InputBatches>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1InputBatchesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1InputBatches>>>
export type GetApiV1InputBatchesQueryError = AxiosError<void>


/**
 * @summary List all inventory batches
 */

export function useGetApiV1InputBatches<TData = Awaited<ReturnType<typeof getApiV1InputBatches>>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1InputBatches>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1InputBatchesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Adds a lot/batch of pesticide or fertilizer to the inventory
 * @summary Register a new input batch (admin only)
 */
export const postApiV1InputBatches = (
    inputBatch: InputBatch, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InputBatch>> => {
    
    
    return axios.post(
      `/api/v1/input-batches`,
      inputBatch,options
    );
  }



export const getPostApiV1InputBatchesMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1InputBatches>>, TError,{data: InputBatch}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1InputBatches>>, TError,{data: InputBatch}, TContext> => {

const mutationKey = ['postApiV1InputBatches'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1InputBatches>>, {data: InputBatch}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1InputBatches(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1InputBatchesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1InputBatches>>>
    export type PostApiV1InputBatchesMutationBody = InputBatch
    export type PostApiV1InputBatchesMutationError = AxiosError<void>

    /**
 * @summary Register a new input batch (admin only)
 */
export const usePostApiV1InputBatches = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1InputBatches>>, TError,{data: InputBatch}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1InputBatches>>,
        TError,
        {data: InputBatch},
        TContext
      > => {

      const mutationOptions = getPostApiV1InputBatchesMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Retrieves stock details for a scanned barcode
 * @summary Look up a batch by GTIN and Lot Number
 */
export const getApiV1InputBatchesLookup = (
    params?: GetApiV1InputBatchesLookupParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InputBatch>> => {
    
    
    return axios.get(
      `/api/v1/input-batches/lookup`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetApiV1InputBatchesLookupQueryKey = (params?: GetApiV1InputBatchesLookupParams,) => {
    return [
    `/api/v1/input-batches/lookup`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1InputBatchesLookupQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1InputBatchesLookup>>, TError = AxiosError<void>>(params?: GetApiV1InputBatchesLookupParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1InputBatchesLookup>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1InputBatchesLookupQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1InputBatchesLookup>>> = ({ signal }) => getApiV1InputBatchesLookup(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1InputBatchesLookup>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1InputBatchesLookupQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1InputBatchesLookup>>>
export type GetApiV1InputBatchesLookupQueryError = AxiosError<void>


/**
 * @summary Look up a batch by GTIN and Lot Number
 */

export function useGetApiV1InputBatchesLookup<TData = Awaited<ReturnType<typeof getApiV1InputBatchesLookup>>, TError = AxiosError<void>>(
 params?: GetApiV1InputBatchesLookupParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1InputBatchesLookup>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1InputBatchesLookupQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




