/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Farm
} from '.././schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Retrieves farms owned by or assigned to the user
 * @summary Get all farms for the current user
 */
export const getApiV1Farms = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Farm[]>> => {
    
    
    return axios.get(
      `/api/v1/farms`,options
    );
  }




export const getGetApiV1FarmsQueryKey = () => {
    return [
    `/api/v1/farms`
    ] as const;
    }

    
export const getGetApiV1FarmsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Farms>>, TError = AxiosError<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1Farms>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1FarmsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Farms>>> = ({ signal }) => getApiV1Farms({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Farms>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1FarmsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Farms>>>
export type GetApiV1FarmsQueryError = AxiosError<void>


/**
 * @summary Get all farms for the current user
 */

export function useGetApiV1Farms<TData = Awaited<ReturnType<typeof getApiV1Farms>>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1Farms>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1FarmsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Registers a new farm owned by the authenticated user
 * @summary Create a new farm
 */
export const postApiV1Farms = (
    farm: Farm, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/api/v1/farms`,
      farm,options
    );
  }



export const getPostApiV1FarmsMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Farms>>, TError,{data: Farm}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Farms>>, TError,{data: Farm}, TContext> => {

const mutationKey = ['postApiV1Farms'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Farms>>, {data: Farm}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Farms(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1FarmsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Farms>>>
    export type PostApiV1FarmsMutationBody = Farm
    export type PostApiV1FarmsMutationError = AxiosError<void>

    /**
 * @summary Create a new farm
 */
export const usePostApiV1Farms = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Farms>>, TError,{data: Farm}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Farms>>,
        TError,
        {data: Farm},
        TContext
      > => {

      const mutationOptions = getPostApiV1FarmsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    