/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Location,
  Uuid
} from '.././schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Retrieves a list of all registered farm locations
 * @summary Get all locations
 */
export const getApiV1Locations = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Location[]>> => {
    
    
    return axios.get(
      `/api/v1/locations`,options
    );
  }




export const getGetApiV1LocationsQueryKey = () => {
    return [
    `/api/v1/locations`
    ] as const;
    }

    
export const getGetApiV1LocationsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Locations>>, TError = AxiosError<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1Locations>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1LocationsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Locations>>> = ({ signal }) => getApiV1Locations({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Locations>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1LocationsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Locations>>>
export type GetApiV1LocationsQueryError = AxiosError<void>


/**
 * @summary Get all locations
 */

export function useGetApiV1Locations<TData = Awaited<ReturnType<typeof getApiV1Locations>>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1Locations>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1LocationsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Registers a new field or facility with its GLN and GeoJSON boundary
 * @summary Create a new farm location
 */
export const postApiV1Locations = (
    location: Location, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Location>> => {
    
    
    return axios.post(
      `/api/v1/locations`,
      location,options
    );
  }



export const getPostApiV1LocationsMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Locations>>, TError,{data: Location}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Locations>>, TError,{data: Location}, TContext> => {

const mutationKey = ['postApiV1Locations'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Locations>>, {data: Location}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Locations(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1LocationsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Locations>>>
    export type PostApiV1LocationsMutationBody = Location
    export type PostApiV1LocationsMutationError = AxiosError<void>

    /**
 * @summary Create a new farm location
 */
export const usePostApiV1Locations = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Locations>>, TError,{data: Location}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Locations>>,
        TError,
        {data: Location},
        TContext
      > => {

      const mutationOptions = getPostApiV1LocationsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Retrieves a specific location by its UUID
 * @summary Get location by ID
 */
export const getApiV1LocationsId = (
    id: Uuid, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Location>> => {
    
    
    return axios.get(
      `/api/v1/locations/${id}`,options
    );
  }




export const getGetApiV1LocationsIdQueryKey = (id?: Uuid,) => {
    return [
    `/api/v1/locations/${id}`
    ] as const;
    }

    
export const getGetApiV1LocationsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1LocationsId>>, TError = AxiosError<void>>(id: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1LocationsId>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1LocationsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1LocationsId>>> = ({ signal }) => getApiV1LocationsId(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1LocationsId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1LocationsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1LocationsId>>>
export type GetApiV1LocationsIdQueryError = AxiosError<void>


/**
 * @summary Get location by ID
 */

export function useGetApiV1LocationsId<TData = Awaited<ReturnType<typeof getApiV1LocationsId>>, TError = AxiosError<void>>(
 id: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1LocationsId>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1LocationsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Removes a location from the system
 * @summary Delete a location
 */
export const deleteApiV1LocationsId = (
    id: Uuid, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/v1/locations/${id}`,options
    );
  }



export const getDeleteApiV1LocationsIdMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1LocationsId>>, TError,{id: Uuid}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1LocationsId>>, TError,{id: Uuid}, TContext> => {

const mutationKey = ['deleteApiV1LocationsId'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1LocationsId>>, {id: Uuid}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1LocationsId(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1LocationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1LocationsId>>>
    
    export type DeleteApiV1LocationsIdMutationError = AxiosError<void>

    /**
 * @summary Delete a location
 */
export const useDeleteApiV1LocationsId = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1LocationsId>>, TError,{id: Uuid}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1LocationsId>>,
        TError,
        {id: Uuid},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1LocationsIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    