/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Media,
  PostApiV1MediaPresignedUrl200,
  PostApiV1MediaPresignedUrlParams,
  Uuid
} from '.././schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Records media metadata after the image has been uploaded to MinIO via presigned URL
 * @summary Record media metadata for an activity log
 */
export const postApiV1Media = (
    media: Media, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Media>> => {
    
    
    return axios.post(
      `/api/v1/media`,
      media,options
    );
  }



export const getPostApiV1MediaMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Media>>, TError,{data: Media}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Media>>, TError,{data: Media}, TContext> => {

const mutationKey = ['postApiV1Media'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Media>>, {data: Media}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Media(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1MediaMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Media>>>
    export type PostApiV1MediaMutationBody = Media
    export type PostApiV1MediaMutationError = AxiosError<void>

    /**
 * @summary Record media metadata for an activity log
 */
export const usePostApiV1Media = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Media>>, TError,{data: Media}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Media>>,
        TError,
        {data: Media},
        TContext
      > => {

      const mutationOptions = getPostApiV1MediaMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Retrieves all media associated with a specific activity log
 * @summary Get media by activity log ID
 */
export const getApiV1MediaActivityActivityLogId = (
    activityLogId: Uuid, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Media[]>> => {
    
    
    return axios.get(
      `/api/v1/media/activity/${activityLogId}`,options
    );
  }




export const getGetApiV1MediaActivityActivityLogIdQueryKey = (activityLogId?: Uuid,) => {
    return [
    `/api/v1/media/activity/${activityLogId}`
    ] as const;
    }

    
export const getGetApiV1MediaActivityActivityLogIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1MediaActivityActivityLogId>>, TError = AxiosError<void>>(activityLogId: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1MediaActivityActivityLogId>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1MediaActivityActivityLogIdQueryKey(activityLogId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1MediaActivityActivityLogId>>> = ({ signal }) => getApiV1MediaActivityActivityLogId(activityLogId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(activityLogId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1MediaActivityActivityLogId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1MediaActivityActivityLogIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1MediaActivityActivityLogId>>>
export type GetApiV1MediaActivityActivityLogIdQueryError = AxiosError<void>


/**
 * @summary Get media by activity log ID
 */

export function useGetApiV1MediaActivityActivityLogId<TData = Awaited<ReturnType<typeof getApiV1MediaActivityActivityLogId>>, TError = AxiosError<void>>(
 activityLogId: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1MediaActivityActivityLogId>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1MediaActivityActivityLogIdQueryOptions(activityLogId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Generates a temporary presigned URL for uploading a photo directly to MinIO in a hierarchical folder structure
 * @summary Get presigned URL for media upload
 */
export const postApiV1MediaPresignedUrl = (
    params?: PostApiV1MediaPresignedUrlParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiV1MediaPresignedUrl200>> => {
    
    
    return axios.post(
      `/api/v1/media/presigned-url`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPostApiV1MediaPresignedUrlMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1MediaPresignedUrl>>, TError,{params?: PostApiV1MediaPresignedUrlParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1MediaPresignedUrl>>, TError,{params?: PostApiV1MediaPresignedUrlParams}, TContext> => {

const mutationKey = ['postApiV1MediaPresignedUrl'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1MediaPresignedUrl>>, {params?: PostApiV1MediaPresignedUrlParams}> = (props) => {
          const {params} = props ?? {};

          return  postApiV1MediaPresignedUrl(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1MediaPresignedUrlMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1MediaPresignedUrl>>>
    
    export type PostApiV1MediaPresignedUrlMutationError = AxiosError<void>

    /**
 * @summary Get presigned URL for media upload
 */
export const usePostApiV1MediaPresignedUrl = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1MediaPresignedUrl>>, TError,{params?: PostApiV1MediaPresignedUrlParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1MediaPresignedUrl>>,
        TError,
        {params?: PostApiV1MediaPresignedUrlParams},
        TContext
      > => {

      const mutationOptions = getPostApiV1MediaPresignedUrlMutationOptions(options);

      return useMutation(mutationOptions);
    }
    