/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ActivityLog,
  Uuid
} from '.././schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Updates details of an activity log. Restricted to admin role.
 * @summary Update or override an existing activity log
 */
export const putApiV1ActivityLogs = (
    activityLog: ActivityLog, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ActivityLog>> => {
    
    
    return axios.put(
      `/api/v1/activity-logs`,
      activityLog,options
    );
  }



export const getPutApiV1ActivityLogsMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1ActivityLogs>>, TError,{data: ActivityLog}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1ActivityLogs>>, TError,{data: ActivityLog}, TContext> => {

const mutationKey = ['putApiV1ActivityLogs'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1ActivityLogs>>, {data: ActivityLog}> = (props) => {
          const {data} = props ?? {};

          return  putApiV1ActivityLogs(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1ActivityLogsMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1ActivityLogs>>>
    export type PutApiV1ActivityLogsMutationBody = ActivityLog
    export type PutApiV1ActivityLogsMutationError = AxiosError<void>

    /**
 * @summary Update or override an existing activity log
 */
export const usePutApiV1ActivityLogs = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1ActivityLogs>>, TError,{data: ActivityLog}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1ActivityLogs>>,
        TError,
        {data: ActivityLog},
        TContext
      > => {

      const mutationOptions = getPutApiV1ActivityLogsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Records a farm activity with GPS coordinates, optionally linked to a task or harvest batch, triggering EPCIS event
 * @summary Create a new activity log
 */
export const postApiV1ActivityLogs = (
    activityLog: ActivityLog, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ActivityLog>> => {
    
    
    return axios.post(
      `/api/v1/activity-logs`,
      activityLog,options
    );
  }



export const getPostApiV1ActivityLogsMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ActivityLogs>>, TError,{data: ActivityLog}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ActivityLogs>>, TError,{data: ActivityLog}, TContext> => {

const mutationKey = ['postApiV1ActivityLogs'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ActivityLogs>>, {data: ActivityLog}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1ActivityLogs(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ActivityLogsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ActivityLogs>>>
    export type PostApiV1ActivityLogsMutationBody = ActivityLog
    export type PostApiV1ActivityLogsMutationError = AxiosError<void>

    /**
 * @summary Create a new activity log
 */
export const usePostApiV1ActivityLogs = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ActivityLogs>>, TError,{data: ActivityLog}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ActivityLogs>>,
        TError,
        {data: ActivityLog},
        TContext
      > => {

      const mutationOptions = getPostApiV1ActivityLogsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Retrieves all activity logs for a specific farm location
 * @summary Get activity logs by location
 */
export const getApiV1ActivityLogsLocationLocationId = (
    locationId: Uuid, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ActivityLog[]>> => {
    
    
    return axios.get(
      `/api/v1/activity-logs/location/${locationId}`,options
    );
  }




export const getGetApiV1ActivityLogsLocationLocationIdQueryKey = (locationId?: Uuid,) => {
    return [
    `/api/v1/activity-logs/location/${locationId}`
    ] as const;
    }

    
export const getGetApiV1ActivityLogsLocationLocationIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ActivityLogsLocationLocationId>>, TError = AxiosError<void>>(locationId: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivityLogsLocationLocationId>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ActivityLogsLocationLocationIdQueryKey(locationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ActivityLogsLocationLocationId>>> = ({ signal }) => getApiV1ActivityLogsLocationLocationId(locationId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(locationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivityLogsLocationLocationId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1ActivityLogsLocationLocationIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ActivityLogsLocationLocationId>>>
export type GetApiV1ActivityLogsLocationLocationIdQueryError = AxiosError<void>


/**
 * @summary Get activity logs by location
 */

export function useGetApiV1ActivityLogsLocationLocationId<TData = Awaited<ReturnType<typeof getApiV1ActivityLogsLocationLocationId>>, TError = AxiosError<void>>(
 locationId: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivityLogsLocationLocationId>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1ActivityLogsLocationLocationIdQueryOptions(locationId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retrieves the activity log associated with a specific task
 * @summary Get activity log by task ID
 */
export const getApiV1ActivityLogsTaskTaskId = (
    taskId: Uuid, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ActivityLog>> => {
    
    
    return axios.get(
      `/api/v1/activity-logs/task/${taskId}`,options
    );
  }




export const getGetApiV1ActivityLogsTaskTaskIdQueryKey = (taskId?: Uuid,) => {
    return [
    `/api/v1/activity-logs/task/${taskId}`
    ] as const;
    }

    
export const getGetApiV1ActivityLogsTaskTaskIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ActivityLogsTaskTaskId>>, TError = AxiosError<void>>(taskId: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivityLogsTaskTaskId>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ActivityLogsTaskTaskIdQueryKey(taskId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ActivityLogsTaskTaskId>>> = ({ signal }) => getApiV1ActivityLogsTaskTaskId(taskId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivityLogsTaskTaskId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1ActivityLogsTaskTaskIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ActivityLogsTaskTaskId>>>
export type GetApiV1ActivityLogsTaskTaskIdQueryError = AxiosError<void>


/**
 * @summary Get activity log by task ID
 */

export function useGetApiV1ActivityLogsTaskTaskId<TData = Awaited<ReturnType<typeof getApiV1ActivityLogsTaskTaskId>>, TError = AxiosError<void>>(
 taskId: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivityLogsTaskTaskId>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1ActivityLogsTaskTaskIdQueryOptions(taskId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retrieves a specific activity log
 * @summary Get activity log by ID
 */
export const getApiV1ActivityLogsId = (
    id: Uuid, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ActivityLog>> => {
    
    
    return axios.get(
      `/api/v1/activity-logs/${id}`,options
    );
  }




export const getGetApiV1ActivityLogsIdQueryKey = (id?: Uuid,) => {
    return [
    `/api/v1/activity-logs/${id}`
    ] as const;
    }

    
export const getGetApiV1ActivityLogsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ActivityLogsId>>, TError = AxiosError<void>>(id: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivityLogsId>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ActivityLogsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ActivityLogsId>>> = ({ signal }) => getApiV1ActivityLogsId(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivityLogsId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1ActivityLogsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ActivityLogsId>>>
export type GetApiV1ActivityLogsIdQueryError = AxiosError<void>


/**
 * @summary Get activity log by ID
 */

export function useGetApiV1ActivityLogsId<TData = Awaited<ReturnType<typeof getApiV1ActivityLogsId>>, TError = AxiosError<void>>(
 id: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivityLogsId>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1ActivityLogsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




