name: farm_recorder_mobile
description: GAP-certified farm activity recorder mobile app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  geolocator: ^11.0.0
  image_picker: ^1.0.7
  image: ^4.1.7
  connectivity_plus: ^5.0.2
  uuid: ^4.3.3
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  record: ^4.4.4 # Downgraded for Linux compatibility

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
  openapi_generator: ^5.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
