/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetApiV1AnalyticsActivitiesParams
} from '.././schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Search activities with optional full-text notes and geo-bounding box
 * @summary Search activities
 */
export const getApiV1AnalyticsActivities = (
    params?: GetApiV1AnalyticsActivitiesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.get(
      `/api/v1/analytics/activities`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetApiV1AnalyticsActivitiesQueryKey = (params?: GetApiV1AnalyticsActivitiesParams,) => {
    return [
    `/api/v1/analytics/activities`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1AnalyticsActivitiesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AnalyticsActivities>>, TError = AxiosError<void>>(params?: GetApiV1AnalyticsActivitiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1AnalyticsActivities>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AnalyticsActivitiesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AnalyticsActivities>>> = ({ signal }) => getApiV1AnalyticsActivities(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AnalyticsActivities>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1AnalyticsActivitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AnalyticsActivities>>>
export type GetApiV1AnalyticsActivitiesQueryError = AxiosError<void>


/**
 * @summary Search activities
 */

export function useGetApiV1AnalyticsActivities<TData = Awaited<ReturnType<typeof getApiV1AnalyticsActivities>>, TError = AxiosError<void>>(
 params?: GetApiV1AnalyticsActivitiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1AnalyticsActivities>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1AnalyticsActivitiesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




