/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  HarvestBatch,
  Uuid
} from '.././schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Retrieves all harvest batches with remaining quantity > 0 for a specific product
 * @summary Get available batches for a product
 */
export const getApiV1HarvestBatchesAvailableProductId = (
    productId: Uuid, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HarvestBatch[]>> => {
    
    
    return axios.get(
      `/api/v1/harvest-batches/available/${productId}`,options
    );
  }




export const getGetApiV1HarvestBatchesAvailableProductIdQueryKey = (productId?: Uuid,) => {
    return [
    `/api/v1/harvest-batches/available/${productId}`
    ] as const;
    }

    
export const getGetApiV1HarvestBatchesAvailableProductIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1HarvestBatchesAvailableProductId>>, TError = AxiosError<void>>(productId: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1HarvestBatchesAvailableProductId>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1HarvestBatchesAvailableProductIdQueryKey(productId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1HarvestBatchesAvailableProductId>>> = ({ signal }) => getApiV1HarvestBatchesAvailableProductId(productId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(productId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1HarvestBatchesAvailableProductId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1HarvestBatchesAvailableProductIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1HarvestBatchesAvailableProductId>>>
export type GetApiV1HarvestBatchesAvailableProductIdQueryError = AxiosError<void>


/**
 * @summary Get available batches for a product
 */

export function useGetApiV1HarvestBatchesAvailableProductId<TData = Awaited<ReturnType<typeof getApiV1HarvestBatchesAvailableProductId>>, TError = AxiosError<void>>(
 productId: Uuid, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1HarvestBatchesAvailableProductId>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1HarvestBatchesAvailableProductIdQueryOptions(productId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




