/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';
import type { Instant } from './instant';
import type { ActivityType } from './activityType';

export interface ActivityLog {
  id?: Uuid;
  timestamp?: Instant;
  userId?: string;
  locationId?: Uuid;
  productId?: Uuid;
  taskId?: Uuid;
  type?: ActivityType;
  notes?: string;
  gpsLat?: number;
  gpsLng?: number;
  startTime?: Instant;
  endTime?: Instant;
  batchId?: Uuid;
  quantity?: number;
  unitPrice?: number;
  totalPrice?: number;
  customerName?: string;
  customerPhone?: string;
  customerEmail?: string;
  chemicalLotNumber?: string;
  chemicalExpirationDate?: Instant;
  applicationRate?: string;
  totalQuantityApplied?: number;
  weatherWindSpeed?: number;
  weatherWindDirection?: string;
  weatherTemperature?: number;
  applicatorLicense?: string;
  isManualInput?: boolean;
  manualInputComments?: string;
  verificationStatus?: string;
  verifiedBy?: string;
  verifiedAt?: Instant;
  reiEndTime?: Instant;
}
