/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';

export interface Farm {
  id?: Uuid;
  name?: string;
  ownerId?: string;
}
