/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1AnalyticsActivitiesParams = {
maxLat?: number;
maxLon?: number;
minLat?: number;
minLon?: number;
notes?: string;
size?: number;
};
