/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */

export type HarvestBatchStatus = typeof HarvestBatchStatus[keyof typeof HarvestBatchStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HarvestBatchStatus = {
  AVAILABLE: 'AVAILABLE',
  DEPLETED: 'DEPLETED',
} as const;
