/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';
import type { Instant } from './instant';
import type { HarvestBatchStatus } from './harvestBatchStatus';

export interface HarvestBatch {
  id?: Uuid;
  productId?: Uuid;
  locationId?: Uuid;
  harvestedById?: string;
  harvestedAt?: Instant;
  batchNumber?: string;
  initialQuantity?: number;
  remainingQuantity?: number;
  status?: HarvestBatchStatus;
}
