/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';
import type { Instant } from './instant';

export interface InputBatch {
  id?: Uuid;
  gtin?: string;
  lotNumber?: string;
  productId?: Uuid;
  initialQuantity?: number;
  remainingQuantity?: number;
  expirationDate?: Instant;
  unit?: string;
  createdAt?: Instant;
}
