/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';
import type { MediaType } from './mediaType';
import type { Instant } from './instant';

export interface Media {
  id?: Uuid;
  activityLogId?: Uuid;
  mediaUrl?: string;
  mediaType?: MediaType;
  capturedGpsLat?: number;
  capturedGpsLng?: number;
  timestamp?: Instant;
}
