/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1MediaPresignedUrlParams = {
contentType?: string;
farmId?: string;
fileName?: string;
taskId?: string;
};
