/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Farm Recorder API
 * API for GAP-certified farm activity recording and EPCIS traceability
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';

export interface Product {
  id?: Uuid;
  gtin?: string;
  name?: string;
  variety?: string;
  batchPrefix?: string;
  defaultUnitPrice?: number;
  type?: string;
  epaRegistrationNumber?: string;
  activeIngredients?: string;
  reiHours?: number;
  phiDays?: number;
  isLocalOnly?: boolean;
  adminNotes?: string;
}
